if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
export PATH=$HOME/.nodebrew/current/bin:$PATH
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
