#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

## MacVim-Kaoriya を Terminal から使う
if [ -f /Applications/MacVim.app/Contents/MacOS/Vim ]; then
    export EDITOR=/Applications/MacVim.app/Contents/MacOS/Vim
    export GIT_EDITOR=$EDITOR
    alias vi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
    alias vim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
fi

# dot config
export DOT_REPO="https://HipBird@bitbucket.org/HipBird/dotfiles.git"
export DOT_DIR="$HOME/.dotfiles"
source $HOME/.dotfiles/bin/dot/dot.sh

# ranger でサブシェルをネストしない
function r() {
    if [ -z "$RANGER_LEVEL" ]; then
        ranger $@
    else
        exit
    fi
}
# ranger から抜けた時オートcd
source $HOME/.config/ranger/plugin/bash_automatic_cd.sh
