[[plugins]]
repo = 'Shougo/echodoc.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repo = 'saihoooooooo/glowshi-ft.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'lambdalisue/vim-findent'
on_path = '.*'

[[plugins]]
repo = 'terryma/vim-expand-region'
on_map = '<Plug>'

[[plugins]]
repo = 'itspriddle/vim-marked'
on_ft = 'markdown'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'thinca/vim-scouter'


[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
external_commands = 'ghc-mod'

[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['html', 'css', 'less', 'scss']

[[plugins]]
repo = 'kana/vim-smartword'
on_map = '<Plug>'

[[plugins]]
repo = 'LeafCage/foldCC'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
on_ft = 'diff'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'
on_ft = 'help'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'
